#### Importing Modules

In [25]:
import numpy as np
from numpy import asarray

#### Data

In [26]:
data = [[3,3,2,1,0], 
        [0,0,1,3,1],
        [3,1,2,2,3],
        [2,0,0,2,2],
        [2,0,0,0,1]]

In [27]:
print(type(data))

<class 'list'>


In [28]:
data = np.asarray(data)
print(type(data))

<class 'numpy.ndarray'>


In [29]:
data = data.reshape(1,5,5,1)
data

array([[[[3],
         [3],
         [2],
         [1],
         [0]],

        [[0],
         [0],
         [1],
         [3],
         [1]],

        [[3],
         [1],
         [2],
         [2],
         [3]],

        [[2],
         [0],
         [0],
         [2],
         [2]],

        [[2],
         [0],
         [0],
         [0],
         [1]]]])

#### Kernel (or) Filter (or) Feature Detector [Convolutional 2D]

In [30]:
#kernel going to 3x3 matrix
kernel = [[[[0]], [[1]], [[2]]],
          [[[2]],[[2]], [[0]]],
          [[[0]], [[1]], [[2]]]]

In [31]:
print(kernel)

[[[[0]], [[1]], [[2]]], [[[2]], [[2]], [[0]]], [[[0]], [[1]], [[2]]]]


In [32]:
weights = [asarray(kernel), asarray([0.0])]
weights

[array([[[[0]],
 
         [[1]],
 
         [[2]]],
 
 
        [[[2]],
 
         [[2]],
 
         [[0]]],
 
 
        [[[0]],
 
         [[1]],
 
         [[2]]]]),
 array([0.])]

In [33]:
print(type(weights))

<class 'list'>


#### Training the Model

#### Kernel 

In [34]:
from keras.models import Sequential
from keras.layers import Conv2D

#create the model
model = Sequential()
model.add(Conv2D(1, (3,3), input_shape = (5,5,1)))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 3, 3, 1)           10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.set_weights(weights)
ythat = model.predict(data)
ythat

1/1 [==============================] - 0s 61ms/step


array([[[[12.],
         [12.],
         [17.]],

        [[10.],
         [17.],
         [19.]],

        [[ 9.],
         [ 6.],
         [14.]]]], dtype=float32)

In [36]:
for r in range(ythat.shape[1]):
    print([ythat[0,r,c,0] for c in range(ythat.shape[2])])

[12.0, 12.0, 17.0]
[10.0, 17.0, 19.0]
[9.0, 6.0, 14.0]


#### Strides

In [37]:
model = Sequential()
model.add(Conv2D(1, (3,3), strides=(2,2), input_shape=(5,5,1)))
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_7 (Conv2D)           (None, 2, 2, 1)           10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [38]:
model.set_weights(weights)
ythat = model.predict(data)
for r in range(ythat.shape[1]):
    print([ythat[0,r,c,0] for c in range(ythat.shape[2])])

1/1 [==============================] - 0s 63ms/step
[12.0, 17.0]
[9.0, 14.0]


#### Padding

In [39]:
model = Sequential()
model.add(Conv2D(1, (3,3), padding="same", input_shape = (5,5,1)))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_8 (Conv2D)           (None, 5, 5, 1)           10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.set_weights(weights)
ythat = model.predict(data)
for r in range(ythat.shape[1]):
    print([ythat[0,r,c,0] for c in range(ythat.shape[1])])

1/1 [==============================] - 0s 79ms/step
[6.0, 14.0, 17.0, 11.0, 3.0]
[14.0, 12.0, 12.0, 17.0, 11.0]
[8.0, 10.0, 17.0, 19.0, 13.0]
[11.0, 9.0, 6.0, 14.0, 12.0]
[6.0, 4.0, 4.0, 6.0, 4.0]


#### Max pooling

In [41]:
from keras.layers import MaxPooling2D
model = Sequential()
model.add(Conv2D(1,(3,3),padding="same", input_shape=(5,5,1)))
model.add(MaxPooling2D((2,2)))
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_9 (Conv2D)           (None, 5, 5, 1)           10        
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 2, 2, 1)          0         
 2D)                                                             
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [42]:
model.set_weights(weights)
ythat = model.predict(data)
for r in range(ythat.shape[1]):
    print([ythat[0,r,c,0] for c in range(ythat.shape[2])])

1/1 [==============================] - 0s 56ms/step
[14.0, 17.0]
[11.0, 19.0]


#### Average Pooling

In [47]:
from keras.layers import AveragePooling2D
model = Sequential()
model.add(Conv2D(1, (3,3), padding="same", input_shape=(5,5,1)))
model.add(AveragePooling2D((2,2)))
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 5, 5, 1)           10        
                                                                 
 average_pooling2d_4 (Averag  (None, 2, 2, 1)          0         
 ePooling2D)                                                     
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [48]:
model.set_weights(weights)
ythat = model.predict(data)
for r in range(ythat.shape[1]):
    print([ythat[0,r,c,0] for c in range(ythat.shape[2])])

1/1 [==============================] - 0s 78ms/step
[11.5, 14.25]
[9.5, 14.0]


#### Flatten

In [45]:
from keras.layers import Flatten
model = Sequential()
model.add(Conv2D(1, (3,3), padding="same", input_shape = (5,5,1)))
model.add(AveragePooling2D((2,2)))
model.add(Flatten())
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_11 (Conv2D)          (None, 5, 5, 1)           10        
                                                                 
 average_pooling2d_3 (Averag  (None, 2, 2, 1)          0         
 ePooling2D)                                                     
                                                                 
 flatten_1 (Flatten)         (None, 4)                 0         
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
